// File: englishVocabulary.js
const vocabData = [
  // --- Unit 1: Family Life ---
  { "word": "benefit", "meaning": ["lợi ích", "phúc lợi", "ưu điểm"], "unit": 1, "grade": 10 },
  { "word": "bond", "meaning": ["sự gắn bó", "kết nối", "mối liên kết"], "unit": 1, "grade": 10 },
  { "word": "breadwinner", "meaning": ["trụ cột gia đình", "người nuôi gia đình", "người kiếm sống"], "unit": 1, "grade": 10 },
  { "word": "character", "meaning": ["tính cách", "nhân vật", "đặc điểm"], "unit": 1, "grade": 10 },
  { "word": "cheer up", "meaning": ["cổ vũ", "làm vui lên", "động viên"], "unit": 1, "grade": 10 },
  { "word": "damage", "meaning": ["phá hỏng", "làm hỏng", "gây hại"], "unit": 1, "grade": 10 },
  { "word": "gratitude", "meaning": ["sự biết ơn", "lòng biết ơn", "tri ân"], "unit": 1, "grade": 10 },
  { "word": "grocery", "meaning": ["tạp hoá", "thực phẩm", "hàng tạp phẩm"], "unit": 1, "grade": 10 },
  { "word": "heavy lifting", "meaning": ["mang vác nặng", "việc nặng", "việc nặng nhọc"], "unit": 1, "grade": 10 },
  { "word": "homemaker", "meaning": ["người nội trợ", "nội trợ", "người làm việc nhà"], "unit": 1, "grade": 10 },
  { "word": "laundry", "meaning": ["giặt là", "đồ giặt", "quần áo giặt"], "unit": 1, "grade": 10 },
  { "word": "manner", "meaning": ["tác phong", "cách ứng xử", "cách cư xử"], "unit": 1, "grade": 10 },
  { "word": "responsibility", "meaning": ["trách nhiệm", "bổn phận", "nghĩa vụ"], "unit": 1, "grade": 10 },
  { "word": "routine", "meaning": ["lệ thường", "thói quen hằng ngày", "công việc hằng ngày"], "unit": 1, "grade": 10 },
  { "word": "rubbish", "meaning": ["rác rưởi", "rác", "đồ bỏ đi"], "unit": 1, "grade": 10 },
  { "word": "spotlessly", "meaning": ["không tì vết", "sạch bong", "tinh tươm"], "unit": 1, "grade": 10 },
  { "word": "strengthen", "meaning": ["củng cố", "làm mạnh thêm", "tăng cường"], "unit": 1, "grade": 10 },
  { "word": "support", "meaning": ["ủng hộ", "hỗ trợ", "giúp đỡ"], "unit": 1, "grade": 10 },
  { "word": "truthful", "meaning": ["trung thực", "thật thà", "đúng sự thật"], "unit": 1, "grade": 10 },
  { "word": "value", "meaning": ["giá trị", "định giá", "chuẩn mực"], "unit": 1, "grade": 10 },
  { "word": "washing-up", "meaning": ["rửa chén bát", "rửa bát", "việc rửa bát"], "unit": 1, "grade": 10 },

  // --- Unit 2: Humans and the Environment ---
  { "word": "adopt", "meaning": ["theo", "chọn theo", "nhận nuôi"], "unit": 2, "grade": 10 },
  { "word": "appliance", "meaning": ["thiết bị", "dụng cụ", "đồ dùng"], "unit": 2, "grade": 10 },
  { "word": "awareness", "meaning": ["nhận thức", "sự hiểu biết", "ý thức"], "unit": 2, "grade": 10 },
  { "word": "calculate", "meaning": ["tính toán", "đo lường", "tính số lượng"], "unit": 2, "grade": 10 },
  { "word": "carbon footprint", "meaning": ["dấu chân cacbon", "vết cacbon", "lượng khí thải cacbon"], "unit": 2, "grade": 10 },
  { "word": "chemical", "meaning": ["hoá chất", "chất hoá học", "thuộc hoá học"], "unit": 2, "grade": 10 },
  { "word": "eco-friendly", "meaning": ["thân thiện môi trường", "tốt cho môi trường", "an toàn cho môi trường"], "unit": 2, "grade": 10 },
  { "word": "electrical", "meaning": ["thuộc về điện", "liên quan đến điện", "dùng điện"], "unit": 2, "grade": 10 },
  { "word": "emission", "meaning": ["sự thải ra", "sự thoát ra", "khí thải"], "unit": 2, "grade": 10 },
  { "word": "encourage", "meaning": ["khuyến khích", "động viên", "thúc đẩy"], "unit": 2, "grade": 10 },
  { "word": "energy", "meaning": ["năng lượng", "nguồn năng lượng", "sức mạnh"], "unit": 2, "grade": 10 },
  { "word": "estimate", "meaning": ["ước tính", "ước lượng", "đánh giá sơ bộ"], "unit": 2, "grade": 10 },
  { "word": "global", "meaning": ["toàn cầu", "thế giới", "khắp thế giới"], "unit": 2, "grade": 10 },
  { "word": "human", "meaning": ["con người", "nhân loại", "người"], "unit": 2, "grade": 10 },
  { "word": "issue", "meaning": ["vấn đề", "sự việc", "ấn phẩm"], "unit": 2, "grade": 10 },
  { "word": "lifestyle", "meaning": ["lối sống", "cách sống", "phong cách sống"], "unit": 2, "grade": 10 },
  { "word": "litter", "meaning": ["rác thải", "xả rác", "rác vụn"], "unit": 2, "grade": 10 },
  { "word": "material", "meaning": ["nguyên liệu", "vật liệu", "chất liệu"], "unit": 2, "grade": 10 },
  { "word": "organic", "meaning": ["hữu cơ", "thuộc cơ thể", "tự nhiên"], "unit": 2, "grade": 10 },
  { "word": "public transport", "meaning": ["giao thông công cộng", "xe công cộng", "phương tiện công cộng"], "unit": 2, "grade": 10 },
  { "word": "refillable", "meaning": ["có thể làm đầy lại", "có thể bơm lại", "thay thế được"], "unit": 2, "grade": 10 },
  { "word": "resource", "meaning": ["tài nguyên", "nguồn lực", "nguồn cung"], "unit": 2, "grade": 10 },
  { "word": "sustainable", "meaning": ["bền vững", "ổn định lâu dài", "có khả năng duy trì"], "unit": 2, "grade": 10 },

  // --- Unit 3: Music ---
  { "word": "bamboo clapper", "meaning": ["phách", "phách tre", "nhạc cụ tre"], "unit": 3, "grade": 10 },
  { "word": "comment", "meaning": ["bình luận", "nhận xét", "lời phê"], "unit": 3, "grade": 10 },
  { "word": "competition", "meaning": ["cuộc thi", "cuộc tranh tài", "sự cạnh tranh"], "unit": 3, "grade": 10 },
  { "word": "concert", "meaning": ["buổi hoà nhạc", "đêm nhạc", "buổi trình diễn"], "unit": 3, "grade": 10 },
  { "word": "decoration", "meaning": ["việc trang trí", "đồ trang trí", "sự trang hoàng"], "unit": 3, "grade": 10 },
  { "word": "delay", "meaning": ["hoãn lại", "chậm trễ", "trì hoãn"], "unit": 3, "grade": 10 },
  { "word": "eliminate", "meaning": ["loại ra", "loại trừ", "loại bỏ"], "unit": 3, "grade": 10 },
  { "word": "judge", "meaning": ["giám khảo", "thẩm phán", "đánh giá"], "unit": 3, "grade": 10 },
  { "word": "live", "meaning": ["trực tiếp", "sống", "sinh sống"], "unit": 3, "grade": 10 },
  { "word": "location", "meaning": ["vị trí", "địa điểm", "nơi ở"], "unit": 3, "grade": 10 },
  { "word": "moon-shaped lute", "meaning": ["đàn nguyệt", "đàn hình trăng", "nguyệt cầm"], "unit": 3, "grade": 10 },
  { "word": "musical instrument", "meaning": ["nhạc cụ", "đồ dùng âm nhạc", "dụng cụ âm nhạc"], "unit": 3, "grade": 10 },
  { "word": "participant", "meaning": ["người tham dự", "người tham gia", "thí sinh"], "unit": 3, "grade": 10 },
  { "word": "performance", "meaning": ["buổi biểu diễn", "buổi trình diễn", "hiệu suất"], "unit": 3, "grade": 10 },
  { "word": "reach", "meaning": ["đạt được", "chạm tới", "vươn tới"], "unit": 3, "grade": 10 },
  { "word": "single", "meaning": ["đĩa đơn", "độc thân", "duy nhất"], "unit": 3, "grade": 10 },
  { "word": "social media", "meaning": ["mạng xã hội", "truyền thông xã hội", "phương tiện xã hội"], "unit": 3, "grade": 10 },
  { "word": "talented", "meaning": ["tài năng", "có khiếu", "giỏi"], "unit": 3, "grade": 10 },
  { "word": "trumpet", "meaning": ["kèn trumpet", "kèn", "chiếc kèn"], "unit": 3, "grade": 10 },
  { "word": "upload", "meaning": ["tải lên", "đưa lên mạng", "cập nhật lên"], "unit": 3, "grade": 10 },

  // --- Unit 4: For a Better Community ---
  { "word": "access", "meaning": ["tiếp cận", "truy cập", "lối vào"], "unit": 4, "grade": 10 },
  { "word": "announcement", "meaning": ["thông báo", "cáo thị", "lời tuyên bố"], "unit": 4, "grade": 10 },
  { "word": "boost", "meaning": ["thúc đẩy", "làm tăng thêm", "đẩy mạnh"], "unit": 4, "grade": 10 },
  { "word": "cheerful", "meaning": ["vui vẻ", "hớn hở", "tươi cười"], "unit": 4, "grade": 10 },
  { "word": "community", "meaning": ["cộng đồng", "dân cư", "xã hội"], "unit": 4, "grade": 10 },
  { "word": "community service", "meaning": ["phục vụ cộng đồng", "dịch vụ cộng đồng", "công tác thiện nguyện"], "unit": 4, "grade": 10 },
  { "word": "confidence", "meaning": ["sự tự tin", "lòng tin", "sự tin tưởng"], "unit": 4, "grade": 10 },
  { "word": "confused", "meaning": ["bối rối", "lúng túng", "nhầm lẫn"], "unit": 4, "grade": 10 },
  { "word": "deliver", "meaning": ["phân phát", "giao hàng", "chuyển phát"], "unit": 4, "grade": 10 },
  { "word": "donate", "meaning": ["cho", "hiến tặng", "quyên góp"], "unit": 4, "grade": 10 },
  { "word": "donation", "meaning": ["đồ hiến tặng", "khoản quyên góp", "sự tặng dữ"], "unit": 4, "grade": 10 },
  { "word": "generous", "meaning": ["hào phóng", "rộng rãi", "quảng đại"], "unit": 4, "grade": 10 },
  { "word": "involved", "meaning": ["tham gia", "dính líu", "liên quan"], "unit": 4, "grade": 10 },
  { "word": "life-saving", "meaning": ["cứu nạn", "cứu sống", "cứu mạng"], "unit": 4, "grade": 10 },
  { "word": "non-governmental", "meaning": ["phi chính phủ", "ngoài chính phủ", "không thuộc nhà nước"], "unit": 4, "grade": 10 },
  { "word": "orphanage", "meaning": ["trại trẻ mồ côi", "nhà tình thương", "cô nhi viện"], "unit": 4, "grade": 10 },
  { "word": "participate", "meaning": ["tham gia", "góp mặt", "dự phần"], "unit": 4, "grade": 10 },
  { "word": "practical", "meaning": ["thực tế", "thiết thực", "có ích"], "unit": 4, "grade": 10 },
  { "word": "raise", "meaning": ["quyên góp", "nâng lên", "nuôi dưỡng"], "unit": 4, "grade": 10 },
  { "word": "remote", "meaning": ["hẻo lánh", "xa xôi", "từ xa"], "unit": 4, "grade": 10 },
  { "word": "various", "meaning": ["đa dạng", "khác nhau", "nhiều loại"], "unit": 4, "grade": 10 },
  { "word": "volunteer", "meaning": ["tình nguyện viên", "tình nguyện", "làm thiện nguyện"], "unit": 4, "grade": 10 },

  // --- Unit 5: Inventions ---
  { "word": "3d printing", "meaning": ["in ba chiều", "in 3d", "công nghệ in 3d"], "unit": 5, "grade": 10 },
  { "word": "ai", "meaning": ["trí tuệ nhân tạo", "trí thông minh nhân tạo", "ai"], "unit": 5, "grade": 10 },
  { "word": "app", "meaning": ["ứng dụng", "phần mềm điện thoại", "app"], "unit": 5, "grade": 10 },
  { "word": "application", "meaning": ["ứng dụng", "đơn xin", "sự áp dụng"], "unit": 5, "grade": 10 },
  { "word": "apply", "meaning": ["áp dụng", "nộp đơn", "thoa lên"], "unit": 5, "grade": 10 },
  { "word": "button", "meaning": ["nút bấm", "nút", "khuy áo"], "unit": 5, "grade": 10 },
  { "word": "charge", "meaning": ["sạc pin", "nạp điện", "tính phí"], "unit": 5, "grade": 10 },
  { "word": "communicate", "meaning": ["giao tiếp", "liên lạc", "truyền đạt"], "unit": 5, "grade": 10 },
  { "word": "computer", "meaning": ["máy tính", "máy vi tính", "thiết bị tính toán"], "unit": 5, "grade": 10 },
  { "word": "device", "meaning": ["thiết bị", "dụng cụ", "linh kiện"], "unit": 5, "grade": 10 },
  { "word": "display", "meaning": ["hiển thị", "trưng bày", "màn hình"], "unit": 5, "grade": 10 },
  { "word": "driverless", "meaning": ["không người lái", "tự động lái", "tự hành"], "unit": 5, "grade": 10 },
  { "word": "e-reader", "meaning": ["thiết bị đọc sách điện tử", "máy đọc sách", "đầu đọc điện tử"], "unit": 5, "grade": 10 },
  { "word": "experiment", "meaning": ["thí nghiệm", "thử nghiệm", "cuộc thí nghiệm"], "unit": 5, "grade": 10 },
  { "word": "hardware", "meaning": ["phần cứng", "thiết bị cứng", "đồ ngũ kim"], "unit": 5, "grade": 10 },
  { "word": "install", "meaning": ["cài đặt", "lắp đặt", "thiết lập"], "unit": 5, "grade": 10 },
  { "word": "invention", "meaning": ["phát minh", "sự sáng chế", "vật sáng chế"], "unit": 5, "grade": 10 },
  { "word": "laboratory", "meaning": ["phòng thí nghiệm", "phòng lab", "phòng nghiên cứu"], "unit": 5, "grade": 10 },
  { "word": "laptop", "meaning": ["máy tính xách tay", "máy tính cá nhân", "laptop"], "unit": 5, "grade": 10 },
  { "word": "processor", "meaning": ["bộ xử lí", "chip xử lý", "máy chế biến"], "unit": 5, "grade": 10 },
  { "word": "ram", "meaning": ["bộ nhớ khả biến", "ram", "bộ nhớ tạm"], "unit": 5, "grade": 10 },
  { "word": "smartphone", "meaning": ["điện thoại thông minh", "smartphone", "điện thoại cảm ứng"], "unit": 5, "grade": 10 },
  { "word": "software", "meaning": ["phần mềm", "chương trình máy tính", "software"], "unit": 5, "grade": 10 },
  { "word": "stain", "meaning": ["vết bẩn", "vết ố", "vết màu"], "unit": 5, "grade": 10 },
  { "word": "storage space", "meaning": ["dung lượng lưu trữ", "không gian lưu trữ", "bộ nhớ lưu trữ"], "unit": 5, "grade": 10 },
  { "word": "store", "meaning": ["lưu trữ", "cửa hàng", "cất giữ"], "unit": 5, "grade": 10 },
  { "word": "suitable", "meaning": ["phù hợp", "thích hợp", "xứng đáng"], "unit": 5, "grade": 10 },
  { "word": "valuable", "meaning": ["có giá trị", "quý giá", "đáng giá"], "unit": 5, "grade": 10 },

  // --- Unit 6: Gender Equality ---
  { "word": "cosmonaut", "meaning": ["nhà du hành vũ trụ", "phi hành gia", "nhà du hành"], "unit": 6, "grade": 10 },
  { "word": "domestic violence", "meaning": ["bạo lực gia đình", "bạo hành gia đình", "ngược đãi trong gia đình"], "unit": 6, "grade": 10 },
  { "word": "equal", "meaning": ["bằng nhau", "bình đẳng", "ngang nhau"], "unit": 6, "grade": 10 },
  { "word": "equality", "meaning": ["sự bình đẳng", "tính ngang hàng", "sự công bằng"], "unit": 6, "grade": 10 },
  { "word": "eyesight", "meaning": ["thị lực", "tầm nhìn", "sức nhìn"], "unit": 6, "grade": 10 },
  { "word": "firefighter", "meaning": ["lính cứu hoả", "lính chữa cháy", "nhân viên cứu hỏa"], "unit": 6, "grade": 10 },
  { "word": "kindergarten", "meaning": ["trường mẫu giáo", "nhà trẻ", "trường mầm non"], "unit": 6, "grade": 10 },
  { "word": "mental", "meaning": ["tinh thần", "tâm thần", "thuộc trí óc"], "unit": 6, "grade": 10 },
  { "word": "officer", "meaning": ["sĩ quan", "viên chức", "cán bộ"], "unit": 6, "grade": 10 },
  { "word": "operation", "meaning": ["cuộc phẫu thuật", "sự vận hành", "hoạt động"], "unit": 6, "grade": 10 },
  { "word": "parachute", "meaning": ["nhảy dù", "cái dù", "dù bay"], "unit": 6, "grade": 10 },
  { "word": "parachutist", "meaning": ["người nhảy dù", "vận động viên nhảy dù", "người dùng dù"], "unit": 6, "grade": 10 },
  { "word": "patient", "meaning": ["bệnh nhân", "kiên nhẫn", "người bệnh"], "unit": 6, "grade": 10 },
  { "word": "physical", "meaning": ["thể chất", "vật lý", "thuộc thân thể"], "unit": 6, "grade": 10 },
  { "word": "pilot", "meaning": ["phi công", "người lái máy bay", "hoa tiêu"], "unit": 6, "grade": 10 },
  { "word": "secretary", "meaning": ["thư kí", "bí thư", "người ghi chép"], "unit": 6, "grade": 10 },
  { "word": "shop assistant", "meaning": ["người bán hàng", "nhân viên bán hàng", "phụ tá cửa hàng"], "unit": 6, "grade": 10 },
  { "word": "skillful", "meaning": ["lành nghề", "khéo léo", "điêu luyện"], "unit": 6, "grade": 10 },
  { "word": "soviet", "meaning": ["liên xô", "thuộc liên xô", "xô viết"], "unit": 6, "grade": 10 },
  { "word": "surgeon", "meaning": ["bác sĩ phẫu thuật", "bác sĩ ngoại khoa", "người mổ"], "unit": 6, "grade": 10 },
  { "word": "uneducated", "meaning": ["ít học", "không được giáo dục", "vô học"], "unit": 6, "grade": 10 },
  { "word": "victim", "meaning": ["nạn nhân", "người bị hại", "vật hy sinh"], "unit": 6, "grade": 10 },

  // --- Unit 7: Viet Nam and International Organisations ---
  { "word": "aim", "meaning": ["mục tiêu", "nhắm đến", "đặt mục tiêu"], "unit": 7, "grade": 10 },
  { "word": "commit", "meaning": ["cam kết", "ủy thác", "phạm lỗi"], "unit": 7, "grade": 10 },
  { "word": "competitive", "meaning": ["cạnh tranh", "có tính đua tranh", "ganh đua"], "unit": 7, "grade": 10 },
  { "word": "economic", "meaning": ["thuộc kinh tế", "liên quan kinh tế", "về kinh tế"], "unit": 7, "grade": 10 },
  { "word": "economy", "meaning": ["nền kinh tế", "sự tiết kiệm", "kinh tế học"], "unit": 7, "grade": 10 },
  { "word": "enter", "meaning": ["thâm nhập", "đi vào", "nhập vào"], "unit": 7, "grade": 10 },
  { "word": "essential", "meaning": ["cần thiết", "thiết yếu", "cấp thiết"], "unit": 7, "grade": 10 },
  { "word": "expert", "meaning": ["chuyên gia", "thuộc chuyên môn", "thành thạo"], "unit": 7, "grade": 10 },
  { "word": "harm", "meaning": ["hiểm hoạ", "sự nguy hiểm", "gây hại"], "unit": 7, "grade": 10 },
  { "word": "invest", "meaning": ["đầu tư", "bỏ vốn", "dành thời gian"], "unit": 7, "grade": 10 },
  { "word": "peacekeeping", "meaning": ["gìn giữ hoà bình", "bảo vệ hoà bình", "duy trì hoà bình"], "unit": 7, "grade": 10 },
  { "word": "poverty", "meaning": ["đói nghèo", "tình trạng nghèo khổ", "sự nghèo nàn"], "unit": 7, "grade": 10 },
  { "word": "promote", "meaning": ["quảng bá", "thăng chức", "khuyến khích"], "unit": 7, "grade": 10 },
  { "word": "quality", "meaning": ["chất lượng", "phẩm chất", "đặc tính"], "unit": 7, "grade": 10 },
  { "word": "regional", "meaning": ["thuộc khu vực", "địa phương", "vùng miền"], "unit": 7, "grade": 10 },
  { "word": "relation", "meaning": ["mối quan hệ", "sự liên quan", "bà con"], "unit": 7, "grade": 10 },
  { "word": "respect", "meaning": ["tôn trọng", "kính trọng", "ghi nhận"], "unit": 7, "grade": 10 },
  { "word": "technical", "meaning": ["thuộc kĩ thuật", "chuyên môn kĩ thuật", "về kĩ thuật"], "unit": 7, "grade": 10 },
  { "word": "trade", "meaning": ["thương mại", "buôn bán", "trao đổi"], "unit": 7, "grade": 10 },
  { "word": "vaccinate", "meaning": ["tiêm vắc-xin", "chủng ngừa", "tiêm phòng"], "unit": 7, "grade": 10 },
  { "word": "welcome", "meaning": ["đón chào", "hoan nghênh", "chào mừng"], "unit": 7, "grade": 10 },

  // --- Unit 8: New Ways to Learn ---
  { "word": "blended learning", "meaning": ["học tập kết hợp", "học hỗn hợp", "phương pháp học kết hợp"], "unit": 8, "grade": 10 },
  { "word": "control", "meaning": ["kiểm soát", "điều khiển", "sự kiểm soát"], "unit": 8, "grade": 10 },
  { "word": "digital", "meaning": ["kĩ thuật số", "điện tử", "số hóa"], "unit": 8, "grade": 10 },
  { "word": "distraction", "meaning": ["xao nhãng", "mất tập trung", "sự làm lơ đãng"], "unit": 8, "grade": 10 },
  { "word": "exchange", "meaning": ["trao đổi", "giao dịch", "đổi chác"], "unit": 8, "grade": 10 },
  { "word": "face-to-face", "meaning": ["trực tiếp", "đối mặt", "giáp mặt"], "unit": 8, "grade": 10 },
  { "word": "flow chart", "meaning": ["lưu đồ", "sơ đồ quy trình", "lược đồ"], "unit": 8, "grade": 10 },
  { "word": "focus", "meaning": ["tập trung", "trung tâm", "tiêu điểm"], "unit": 8, "grade": 10 },
  { "word": "high-speed", "meaning": ["tốc độ cao", "siêu tốc", "nhanh"], "unit": 8, "grade": 10 },
  { "word": "immediately", "meaning": ["ngay lập tức", "tức thì", "ngay"], "unit": 8, "grade": 10 },
  { "word": "install", "meaning": ["lắp đặt", "cài đặt", "thiết lập"], "unit": 8, "grade": 10 },
  { "word": "online learning", "meaning": ["học trực tuyến", "học trên mạng", "học online"], "unit": 8, "grade": 10 },
  { "word": "original", "meaning": ["sáng tạo", "độc đáo", "nguyên bản"], "unit": 8, "grade": 10 },
  { "word": "real-world", "meaning": ["thực tế", "thế giới thực", "ngoài đời"], "unit": 8, "grade": 10 },
  { "word": "schedule", "meaning": ["lịch trình", "thời gian biểu", "kế hoạch"], "unit": 8, "grade": 10 },
  { "word": "strategy", "meaning": ["chiến lược", "kế sách", "phương lược"], "unit": 8, "grade": 10 },
  { "word": "teamwork", "meaning": ["hoạt động nhóm", "làm việc nhóm", "tinh thần đồng đội"], "unit": 8, "grade": 10 },
  { "word": "voice recorder", "meaning": ["máy thu âm", "máy ghi âm", "thiết bị thu âm"], "unit": 8, "grade": 10 },

  // --- Unit 9: Protecting the Environment ---
  { "word": "balance", "meaning": ["sự cân bằng", "thăng bằng", "số dư"], "unit": 9, "grade": 10 },
  { "word": "biodiversity", "meaning": ["đa dạng sinh học", "sự phong phú sinh học", "hệ sinh thái đa dạng"], "unit": 9, "grade": 10 },
  { "word": "climate change", "meaning": ["biến đổi khí hậu", "thay đổi khí hậu", "khí hậu biến đổi"], "unit": 9, "grade": 10 },
  { "word": "consequence", "meaning": ["hậu quả", "kết quả", "hệ quả"], "unit": 9, "grade": 10 },
  { "word": "deforestation", "meaning": ["nạn phá rừng", "sự phá rừng", "việc chặt phá rừng"], "unit": 9, "grade": 10 },
  { "word": "ecosystem", "meaning": ["hệ sinh thái", "hệ môi trường", "vùng sinh thái"], "unit": 9, "grade": 10 },
  { "word": "endangered", "meaning": ["bị nguy hiểm", "đang gặp nguy hiểm", "có nguy cơ tuyệt chủng"], "unit": 9, "grade": 10 },
  { "word": "environmental protection", "meaning": ["bảo vệ môi trường", "giữ gìn môi trường", "phòng hộ môi trường"], "unit": 9, "grade": 10 },
  { "word": "extreme", "meaning": ["cực đoan", "khắc nghiệt", "vô cùng"], "unit": 9, "grade": 10 },
  { "word": "giant", "meaning": ["khổng lồ", "to lớn", "người khổng lồ"], "unit": 9, "grade": 10 },
  { "word": "habitat", "meaning": ["môi trường sống", "nơi ở tự nhiên", "trú xứ"], "unit": 9, "grade": 10 },
  { "word": "heatwave", "meaning": ["sóng nhiệt", "đợt nắng nóng", "đợt không khí nóng"], "unit": 9, "grade": 10 },
  { "word": "ice melting", "meaning": ["sự tan băng", "băng tan", "việc tan chảy băng"], "unit": 9, "grade": 10 },
  { "word": "panda", "meaning": ["gấu trúc", "con gấu trúc", "gấu trúc lớn"], "unit": 9, "grade": 10 },
  { "word": "respiratory", "meaning": ["thuộc hô hấp", "về đường thở", "liên quan hô hấp"], "unit": 9, "grade": 10 },
  { "word": "tortoise", "meaning": ["con rùa", "rùa cạn", "con rùa đất"], "unit": 9, "grade": 10 },
  { "word": "upset", "meaning": ["làm rối loạn", "xáo trộn", "buồn phiền"], "unit": 9, "grade": 10 },
  { "word": "wildlife", "meaning": ["động vật hoang dã", "sinh vật hoang dã", "thế giới tự nhiên"], "unit": 9, "grade": 10 },

  // --- Unit 10: Ecotourism ---
  { "word": "aware", "meaning": ["có nhận thức", "ý thức được", "biết về"], "unit": 10, "grade": 10 },
  { "word": "brochure", "meaning": ["tờ quảng cáo", "tờ rơi", "sách hướng dẫn"], "unit": 10, "grade": 10 },
  { "word": "craft", "meaning": ["đồ thủ công", "nghề thủ công", "kỹ năng"], "unit": 10, "grade": 10 },
  { "word": "crowd", "meaning": ["đổ về", "đám đông", "kéo về"], "unit": 10, "grade": 10 },
  { "word": "culture", "meaning": ["văn hoá", "sự nuôi cấy", "nền văn hóa"], "unit": 10, "grade": 10 },
  { "word": "damage", "meaning": ["làm hư hại", "gây thiệt hại", "tàn phá"], "unit": 10, "grade": 10 },
  { "word": "ecotourism", "meaning": ["du lịch sinh thái", "du lịch xanh", "du lịch bền vững"], "unit": 10, "grade": 10 },
  { "word": "explore", "meaning": ["khám phá", "thăm dò", "tìm hiểu"], "unit": 10, "grade": 10 },
  { "word": "floating market", "meaning": ["chợ nổi", "chợ trên sông", "thị trường nổi"], "unit": 10, "grade": 10 },
  { "word": "follow", "meaning": ["đi theo", "theo dõi", "tuân thủ"], "unit": 10, "grade": 10 },
  { "word": "host", "meaning": ["chủ nhà", "người dẫn chương trình", "đăng cai"], "unit": 10, "grade": 10 },
  { "word": "hunt", "meaning": ["săn bắn", "tìm kiếm", "cuộc săn"], "unit": 10, "grade": 10 },
  { "word": "impact", "meaning": ["tác động", "ảnh hưởng", "va chạm"], "unit": 10, "grade": 10 },
  { "word": "local", "meaning": ["địa phương", "tại chỗ", "dân địa phương"], "unit": 10, "grade": 10 },
  { "word": "mass", "meaning": ["số đông", "khối lượng", "đại chúng"], "unit": 10, "grade": 10 },
  { "word": "path", "meaning": ["lối đi", "con đường", "đường dẫn"], "unit": 10, "grade": 10 },
  { "word": "profit", "meaning": ["lợi nhuận", "tiền lãi", "lợi ích"], "unit": 10, "grade": 10 },
  { "word": "protect", "meaning": ["bảo vệ", "che chở", "phòng vệ"], "unit": 10, "grade": 10 },
  { "word": "responsible", "meaning": ["có trách nhiệm", "đáng tin cậy", "phụ trách"], "unit": 10, "grade": 10 },
  { "word": "souvenir", "meaning": ["quà lưu niệm", "vật kỷ niệm", "đồ lưu niệm"], "unit": 10, "grade": 10 },
  { "word": "stalactite", "meaning": ["nhũ đá", "thạch nhũ", "đá trong hang"], "unit": 10, "grade": 10 },
  { "word": "trail", "meaning": ["đường mòn", "vệt dài", "đường đi"], "unit": 10, "grade": 10 },
  { "word": "waste", "meaning": ["lãng phí", "rác thải", "phung phí"], "unit": 10, "grade": 10 },
  { "word": "weave", "meaning": ["dệt", "đan", "kết lại"], "unit": 10, "grade": 10 },












    //Grade11
  // UNIT 1
  { word: "Antibiotic", meaning: ["thuốc kháng sinh", "kháng sinh"], unit: 1, grade: 11 },
  { word: "Bacteria", meaning: ["vi khuẩn"], unit: 1, grade: 11 },
  { word: "Balanced", meaning: ["cân bằng", "cân đối"], unit: 1, grade: 11 },
  { word: "Cut down on", meaning: ["cắt giảm"], unit: 1, grade: 11 },
  { word: "Diameter", meaning: ["đường kính"], unit: 1, grade: 11 },
  { word: "Disease", meaning: ["bệnh", "bệnh tật"], unit: 1, grade: 11 },
  { word: "Energy", meaning: ["sinh lực", "nghị lực", "năng lượng"], unit: 1, grade: 11 },
  { word: "Examine", meaning: ["xem xét", "nghiên cứu", "khám bệnh", "kiểm tra"], unit: 1, grade: 11 },
  { word: "Fitness", meaning: ["sự mạnh khỏe", "sự sung sức", "sự phù hợp", "sự thích hợp"], unit: 1, grade: 11 },
  { word: "Food poisoning", meaning: ["ngộ độc thức ăn"], unit: 1, grade: 11 },
  { word: "Germ", meaning: ["vi trùng"], unit: 1, grade: 11 },
  { word: "Give up", meaning: ["từ bỏ"], unit: 1, grade: 11 },
  { word: "Infection", meaning: ["bệnh lây nhiễm", "sự lây nhiễm"], unit: 1, grade: 11 },
  { word: "Ingredient", meaning: ["thành phần"], unit: 1, grade: 11 },
  { word: "Life expectancy", meaning: ["tuổi thọ"], unit: 1, grade: 11 },
  { word: "Muscle", meaning: ["sức mạnh cơ bắp"], unit: 1, grade: 11 },
  { word: "Nutrient", meaning: ["chất dinh dưỡng"], unit: 1, grade: 11 },
  { word: "Organism", meaning: ["sinh vật", "thực thể sống"], unit: 1, grade: 11 },
  { word: "Press-up", meaning: ["động tác chống đẩy"], unit: 1, grade: 11 },
  { word: "Properly", meaning: ["một cách điều độ", "hợp lí"], unit: 1, grade: 11 },
  { word: "Recipe", meaning: ["cách nấu nướng", "công thức chế biến"], unit: 1, grade: 11 },
  { word: "Regular", meaning: ["đều", "đều đặn"], unit: 1, grade: 11 },
  { word: "Spread", meaning: ["sự truyền bá", "sự lan truyền"], unit: 1, grade: 11 },
  { word: "Star jump", meaning: ["động tác nhảy dang tay chân"], unit: 1, grade: 11 },
  { word: "Strength", meaning: ["sức mạnh", "sức"], unit: 1, grade: 11 },
  { word: "Suffer", meaning: ["chịu đựng"], unit: 1, grade: 11 },
  { word: "Treatment", meaning: ["sự điều trị", "cuộc điều trị", "thuốc điều trị"], unit: 1, grade: 11 },
  { word: "Tuberculosis", meaning: ["bệnh lao"], unit: 1, grade: 11 },
  { word: "Virus", meaning: ["vi-rút", "virus"], unit: 1, grade: 11 },
  { word: "Work out", meaning: ["tập thể dục"], unit: 1, grade: 11 },

  // UNIT 2
  { word: "Generation gap", meaning: ["khoảng cách giữa các thế hệ"], unit: 2, grade: 11 },
  { word: "Adapt", meaning: ["làm cho hợp với", "sửa cho hợp với"], unit: 2, grade: 11 },
  { word: "Argument", meaning: ["sự tranh luận", "sự bàn cãi"], unit: 2, grade: 11 },
  { word: "Characteristic", meaning: ["đặc thù", "đặc trưng", "riêng"], unit: 2, grade: 11 },
  { word: "Conflict", meaning: ["sự mâu thuẫn", "sự đối lập"], unit: 2, grade: 11 },
  { word: "Curious", meaning: ["ham hiểu biết", "tò mò", "hiếu kỳ"], unit: 2, grade: 11 },
  { word: "Digital native", meaning: ["người được sinh ra ở thời đại công nghệ"], unit: 2, grade: 11 },
  { word: "Experience", meaning: ["trải nghiệm"], unit: 2, grade: 11 },
  { word: "Extended family", meaning: ["gia đình đa thế hệ", "đại gia đình"], unit: 2, grade: 11 },
  { word: "Freedom", meaning: ["sự tự do", "quyền tự do"], unit: 2, grade: 11 },
  { word: "Hire", meaning: ["thuê", "mướn"], unit: 2, grade: 11 },
  { word: "Honesty", meaning: ["tính trung thực", "tính chân thật"], unit: 2, grade: 11 },
  { word: "Individualism", meaning: ["chủ nghĩa cá nhân"], unit: 2, grade: 11 },
  { word: "Influence", meaning: ["gây ảnh hưởng"], unit: 2, grade: 11 },
  { word: "Limit", meaning: ["giới hạn"], unit: 2, grade: 11 },
  { word: "Screen time", meaning: ["thời gian sử dụng thiết bị điện tử"], unit: 2, grade: 11 },
  { word: "Social media", meaning: ["phương tiện truyền thông mạng xã hội", "mạng xã hội"], unit: 2, grade: 11 },
  { word: "Value", meaning: ["giá trị", "coi trọng"], unit: 2, grade: 11 },
  { word: "View", meaning: ["quan điểm"], unit: 2, grade: 11 },
  { word: "Bridge the gap", meaning: ["giảm thiểu sự khác biệt"], unit: 2, grade: 11 },
  { word: "Curfew", meaning: ["lệnh giới nghiêm"], unit: 2, grade: 11 },
  { word: "Attitude", meaning: ["thái độ"], unit: 2, grade: 11 },
  { word: "Burden", meaning: ["gánh nặng"], unit: 2, grade: 11 },
  { word: "Mature", meaning: ["trưởng thành", "chín chắn"], unit: 2, grade: 11 },
  { word: "Norm", meaning: ["chuẩn mực"], unit: 2, grade: 11 },
  { word: "Obey", meaning: ["vâng lời", "tuân thủ"], unit: 2, grade: 11 },
  { word: "Financial burden", meaning: ["gánh nặng tài chính"], unit: 2, grade: 11 },
  { word: "Follow in one's footsteps", meaning: ["theo bước", "nối nghiệp"], unit: 2, grade: 11 },
  { word: "Multi-generational", meaning: ["đa thế hệ", "nhiều thế hệ"], unit: 2, grade: 11 },
  { word: "Objection", meaning: ["sự phản kháng"], unit: 2, grade: 11 },
  { word: "Open-minded", meaning: ["cởi mở"], unit: 2, grade: 11 },
  { word: "Impose", meaning: ["áp đặt"], unit: 2, grade: 11 },
  { word: "Elegant", meaning: ["thanh lịch", "tao nhã"], unit: 2, grade: 11 },
  { word: "Flashy", meaning: ["diện", "hào nhoáng"], unit: 2, grade: 11 },

  // UNIT 3
  { word: "Article", meaning: ["bài báo"], unit: 3, grade: 11 },
  { word: "Card reader", meaning: ["thiết bị đọc thẻ"], unit: 3, grade: 11 },
  { word: "City dweller", meaning: ["người sống ở đô thị", "cư dân thành thị"], unit: 3, grade: 11 },
  { word: "Cycle path", meaning: ["làn đường dành cho xe đạp"], unit: 3, grade: 11 },
  { word: "Efficiently", meaning: ["có năng suất", "hiệu suất cao"], unit: 3, grade: 11 },
  { word: "High-rise", meaning: ["cao tầng", "nhiều tầng"], unit: 3, grade: 11 },
  { word: "Infrastructure", meaning: ["cơ sở hạ tầng"], unit: 3, grade: 11 },
  { word: "Interact", meaning: ["tác động qua lại"], unit: 3, grade: 11 },
  { word: "Liveable", meaning: ["đáng sống"], unit: 3, grade: 11 },
  { word: "Neighborhood", meaning: ["khu dân cư"], unit: 3, grade: 11 },
  { word: "Operate", meaning: ["hoạt động", "vận hành", "chạy"], unit: 3, grade: 11 },
  { word: "Pedestrian", meaning: ["người đi bộ", "khách bộ hành"], unit: 3, grade: 11 },
  { word: "Privacy", meaning: ["sự riêng tư"], unit: 3, grade: 11 },
  { word: "Roof garden", meaning: ["vườn trên sân thượng"], unit: 3, grade: 11 },
  { word: "Sense of community", meaning: ["ý thức cộng đồng"], unit: 3, grade: 11 },
  { word: "Sensor", meaning: ["cảm biến"], unit: 3, grade: 11 },
  { word: "Skyscraper", meaning: ["nhà chọc trời"], unit: 3, grade: 11 },
  { word: "Smart city", meaning: ["thành phố thông minh"], unit: 3, grade: 11 },
  { word: "Sustainable", meaning: ["bền vững", "có thể chịu đựng được"], unit: 3, grade: 11 },
  { word: "Urban centre", meaning: ["khu đô thị", "trung tâm đô thị"], unit: 3, grade: 11 },
  { word: "Upgrade", meaning: ["nâng cấp"], unit: 3, grade: 11 },
  { word: "Urban planner", meaning: ["người quy hoạch đô thị", "chuyên gia quy hoạch đô thị"], unit: 3, grade: 11 },
  { word: "Optimistic", meaning: ["lạc quan"], unit: 3, grade: 11 },
  { word: "Overcrowded", meaning: ["chật ních", "đông nghẹt"], unit: 3, grade: 11 },
  { word: "Pessimistic", meaning: ["bi quan"], unit: 3, grade: 11 },
  { word: "Quality of life", meaning: ["chất lượng sống"], unit: 3, grade: 11 },
  { word: "Renewable", meaning: ["có thể tái tạo lại"], unit: 3, grade: 11 },
  { word: "Inhabitant", meaning: ["cư dân", "người cư trú"], unit: 3, grade: 11 },
  { word: "Detect", meaning: ["dò tìm", "phát hiện ra"], unit: 3, grade: 11 },
  { word: "Metropolitan", meaning: ["thuộc thủ đô", "ở thủ đô"], unit: 3, grade: 11 },
  { word: "Cosmopolitan", meaning: ["gồm người từ nhiều nước", "gồm người tứ xứ"], unit: 3, grade: 11 },

  // UNIT 4
  { word: "Apply", meaning: ["xin việc", "ứng cử"], unit: 4, grade: 11 },
  { word: "Celebration", meaning: ["sự kỷ niệm", "lễ kỷ niệm"], unit: 4, grade: 11 },
  { word: "Community", meaning: ["cộng đồng"], unit: 4, grade: 11 },
  { word: "Cultural exchange", meaning: ["sự trao đổi văn hóa"], unit: 4, grade: 11 },
  { word: "Current", meaning: ["hiện hành", "đang lưu hành"], unit: 4, grade: 11 },
  { word: "Eye-opening", meaning: ["mở mang tầm mắt"], unit: 4, grade: 11 },
  { word: "Honour", meaning: ["danh dự", "vinh dự"], unit: 4, grade: 11 },
  { word: "Issue", meaning: ["vấn đề"], unit: 4, grade: 11 },
  { word: "Leadership skill", meaning: ["kĩ năng lãnh đạo"], unit: 4, grade: 11 },
  { word: "Live-stream", meaning: ["phát sóng trực tiếp"], unit: 4, grade: 11 },
  { word: "Politics", meaning: ["chính trị"], unit: 4, grade: 11 },
  { word: "Promote", meaning: ["thúc đẩy", "khuyến mại", "quảng bá"], unit: 4, grade: 11 },
  { word: "Proposal", meaning: ["sự đề nghị", "đề xuất"], unit: 4, grade: 11 },
  { word: "Qualify", meaning: ["đủ tiêu chuẩn", "đủ khả năng"], unit: 4, grade: 11 },
  { word: "Region", meaning: ["vùng", "miền", "khu vực"], unit: 4, grade: 11 },
  { word: "Relation", meaning: ["mối quan hệ", "mối liên quan"], unit: 4, grade: 11 },
  { word: "Representative", meaning: ["người đại diện"], unit: 4, grade: 11 },
  { word: "Strengthen", meaning: ["củng cố", "tăng cường"], unit: 4, grade: 11 },
  { word: "Support", meaning: ["ủng hộ"], unit: 4, grade: 11 },
  { word: "Volunteer", meaning: ["tình nguyện", "tình nguyện viên"], unit: 4, grade: 11 },
  { word: "Youth", meaning: ["tuổi trẻ", "tuổi thanh niên", "tuổi niên thiếu"], unit: 4, grade: 11 },
  { word: "Interference", meaning: ["sự can thiệp"], unit: 4, grade: 11 },
  { word: "Maintain", meaning: ["duy trì"], unit: 4, grade: 11 },
  { word: "Principle", meaning: ["nguyên tắc"], unit: 4, grade: 11 },
  { word: "Scholarship", meaning: ["học bổng"], unit: 4, grade: 11 },
  { word: "Solidarity", meaning: ["sự đoàn kết"], unit: 4, grade: 11 },
  { word: "Stability", meaning: ["sự ổn định"], unit: 4, grade: 11 },
  { word: "Internal", meaning: ["ở trong", "bên trong"], unit: 4, grade: 11 },
  { word: "Motto", meaning: ["khẩu hiệu", "phương châm"], unit: 4, grade: 11 },
  { word: "Official", meaning: ["chính thức"], unit: 4, grade: 11 },
  { word: "Sponsor", meaning: ["nhà tài trợ"], unit: 4, grade: 11 },
  { word: "Vision", meaning: ["tầm nhìn"], unit: 4, grade: 11 },
  { word: "Conference", meaning: ["hội nghị"], unit: 4, grade: 11 },
  { word: "Constitution", meaning: ["hiến pháp"], unit: 4, grade: 11 },
  { word: "Dispute", meaning: ["cuộc tranh luận", "cuộc tranh chấp"], unit: 4, grade: 11 },
  { word: "Block", meaning: ["khối"], unit: 4, grade: 11 },
  { word: "Graceful", meaning: ["duyên dáng", "yêu kiều"], unit: 4, grade: 11 },

  // UNIT 5
  { word: "Global warming", meaning: ["sự nóng lên toàn cầu"], unit: 5, grade: 11 },
  { word: "Atmosphere", meaning: ["khí quyển"], unit: 5, grade: 11 },
  { word: "Balance", meaning: ["sự cân bằng", "sự cân đối"], unit: 5, grade: 11 },
  { word: "Carbon dioxide", meaning: ["khí cacbonic"], unit: 5, grade: 11 },
  { word: "Coal", meaning: ["than đá"], unit: 5, grade: 11 },
  { word: "Consequence", meaning: ["hậu quả"], unit: 5, grade: 11 },
  { word: "Cut down", meaning: ["chặt", "đốn"], unit: 5, grade: 11 },
  { word: "Deforestation", meaning: ["sự phá rừng", "sự phát quang"], unit: 5, grade: 11 },
  { word: "Emission", meaning: ["sự phát ra", "sự bốc ra", "sự tỏa ra"], unit: 5, grade: 11 },
  { word: "Environment", meaning: ["môi trường"], unit: 5, grade: 11 },
  { word: "Farming", meaning: ["nghề nông"], unit: 5, grade: 11 },
  { word: "Fossil fuel", meaning: ["nhiên liệu hóa thạch"], unit: 5, grade: 11 },
  { word: "Heat-trapping", meaning: ["giữ nhiệt"], unit: 5, grade: 11 },
  { word: "Human activity", meaning: ["hoạt động của con người"], unit: 5, grade: 11 },
  { word: "Impact", meaning: ["sự tác động", "ảnh hưởng"], unit: 5, grade: 11 },
  { word: "Leaflet", meaning: ["tờ quảng cáo rời"], unit: 5, grade: 11 },
  { word: "Methane", meaning: ["metan"], unit: 5, grade: 11 },
  { word: "Pollutant", meaning: ["chất gây ô nhiễm", "chất ô nhiễm"], unit: 5, grade: 11 },
  { word: "Release", meaning: ["giải thoát", "thải ra"], unit: 5, grade: 11 },
  { word: "Renewable", meaning: ["có thể tái tạo", "có thể gia hạn được"], unit: 5, grade: 11 },
  { word: "Sea level", meaning: ["mực nước biển"], unit: 5, grade: 11 },
  { word: "Soil", meaning: ["đất trồng"], unit: 5, grade: 11 },
  { word: "Soot", meaning: ["bồ hóng", "nhọ nồi", "muội"], unit: 5, grade: 11 },
  { word: "Temperature", meaning: ["nhiệt độ"], unit: 5, grade: 11 },
  { word: "Waste", meaning: ["đồ phế thải", "rác"], unit: 5, grade: 11 },
  { word: "Campaign", meaning: ["chiến dịch"], unit: 5, grade: 11 },
  { word: "Biodiversity", meaning: ["đa dạng sinh học"], unit: 5, grade: 11 },
  { word: "Vulnerable", meaning: ["dễ bị tổn thương", "dễ gặp nguy hiểm"], unit: 5, grade: 11 },
  { word: "Habitat", meaning: ["môi trường sống"], unit: 5, grade: 11 },
  { word: "Extinct", meaning: ["tuyệt chủng"], unit: 5, grade: 11 },
  { word: "Conservation", meaning: ["sự bảo tồn"], unit: 5, grade: 11 },
  { word: "Survive", meaning: ["sống sót"], unit: 5, grade: 11 },

  // UNIT 6
  { word: "ancient", meaning: ["cổ kính"], unit: 6, grade: 11 },
  { word: "appreciate", meaning: ["hiểu rõ giá trị", "đánh giá cao"], unit: 6, grade: 11 },
  { word: "citadel", meaning: ["thành trì"], unit: 6, grade: 11 },
  { word: "complex", meaning: ["quần thể", "tổ hợp"], unit: 6, grade: 11 },
  { word: "crowdfunding", meaning: ["quyên góp", "huy động vốn từ cộng đồng"], unit: 6, grade: 11 },
  { word: "festive", meaning: ["thuộc về ngày lễ", "có không khí lễ hội"], unit: 6, grade: 11 },
  { word: "fine", meaning: ["tiền phạt"], unit: 6, grade: 11 },
  { word: "folk", meaning: ["thuộc về dân gian"], unit: 6, grade: 11 },
  { word: "heritage", meaning: ["di sản"], unit: 6, grade: 11 },
  { word: "historic", meaning: ["quan trọng", "có giá trị lịch sử"], unit: 6, grade: 11 },
  { word: "historical", meaning: ["thuộc về lịch sử", "mang tính lịch sử"], unit: 6, grade: 11 },
  { word: "imperial", meaning: ["thuộc về hoàng tộc"], unit: 6, grade: 11 },
  { word: "landscape", meaning: ["phong cảnh"], unit: 6, grade: 11 },
  { word: "limestone", meaning: ["đá vôi"], unit: 6, grade: 11 },
  { word: "monument", meaning: ["lăng mộ", "đài kỷ niệm", "công trình kiến trúc"], unit: 6, grade: 11 },
  { word: "performing arts", meaning: ["nghệ thuật biểu diễn"], unit: 6, grade: 11 },
  { word: "preserve", meaning: ["bảo tồn"], unit: 6, grade: 11 },
  { word: "restore", meaning: ["khôi phục", "sửa lại"], unit: 6, grade: 11 },
  { word: "state", meaning: ["hiện trạng", "tình trạng"], unit: 6, grade: 11 },
  { word: "temple", meaning: ["đền", "miếu"], unit: 6, grade: 11 },
  { word: "trending", meaning: ["theo xu hướng"], unit: 6, grade: 11 },
  { word: "valley", meaning: ["thung lũng"], unit: 6, grade: 11 },

  // UNIT 7
  { word: "academic", meaning: ["có tính chất học thuật", "liên quan tới học tập"], unit: 7, grade: 11 },
  { word: "apprenticeship", meaning: ["thời gian học nghề", "học việc thực tế"], unit: 7, grade: 11 },
  { word: "bachelor’s degree", meaning: ["bằng cử nhân"], unit: 7, grade: 11 },
  { word: "brochure", meaning: ["ấn phẩm quảng cáo", "giới thiệu"], unit: 7, grade: 11 },
  { word: "doctorate", meaning: ["bằng tiến sĩ"], unit: 7, grade: 11 },
  { word: "entrance exam", meaning: ["kì thi đầu vào"], unit: 7, grade: 11 },
  { word: "formal", meaning: ["chính quy", "có hệ thống"], unit: 7, grade: 11 },
  { word: "graduation", meaning: ["khi tốt nghiệp", "lễ tốt nghiệp"], unit: 7, grade: 11 },
  { word: "higher education", meaning: ["giáo dục đại học"], unit: 7, grade: 11 },
  { word: "institution", meaning: ["cơ sở", "viện đào tạo"], unit: 7, grade: 11 },
  { word: "manage", meaning: ["cố gắng", "quản lí"], unit: 7, grade: 11 },
  { word: "master’s degree", meaning: ["bằng thạc sĩ"], unit: 7, grade: 11 },
  { word: "mechanic", meaning: ["thợ cơ khí"], unit: 7, grade: 11 },
  { word: "professional", meaning: ["chuyên nghiệp", "nhà nghề"], unit: 7, grade: 11 },
  { word: "qualification", meaning: ["trình độ chuyên môn", "văn bằng"], unit: 7, grade: 11 },
  { word: "school-leaver", meaning: ["học sinh tốt nghiệp trung học phổ thông"], unit: 7, grade: 11 },
  { word: "sixth-form college", meaning: ["trường dự bị đại học", "trường dành cho học sinh từ 16-19 tuổi"], unit: 7, grade: 11 },
  { word: "vocational school", meaning: ["trường dạy nghề"], unit: 7, grade: 11 },

  // UNIT 8
  { word: "achieve", meaning: ["đạt được", "giành được"], unit: 8, grade: 11 },
  { word: "carry out", meaning: ["tiến hành"], unit: 8, grade: 11 },
  { word: "combine", meaning: ["kết hợp"], unit: 8, grade: 11 },
  { word: "come up with", meaning: ["nghĩ ra", "nảy ra"], unit: 8, grade: 11 },
  { word: "confidence", meaning: ["sự tự tin"], unit: 8, grade: 11 },
  { word: "confident", meaning: ["tự tự tin"], unit: 8, grade: 11 },
  { word: "deal with", meaning: ["giải quyết", "đối phó"], unit: 8, grade: 11 },
  { word: "decision making skill", meaning: ["kĩ năng đưa ra quyết định"], unit: 8, grade: 11 },
  { word: "get around", meaning: ["đi lại"], unit: 8, grade: 11 },
  { word: "get into the habit of", meaning: ["tạo thói quen"], unit: 8, grade: 11 },
  { word: "independence", meaning: ["sự độc lập"], unit: 8, grade: 11 },
  { word: "independent", meaning: ["độc lập", "không lệ thuộc"], unit: 8, grade: 11 },
  { word: "learner", meaning: ["người học"], unit: 8, grade: 11 },
  { word: "learning goal", meaning: ["mục tiêu học tập"], unit: 8, grade: 11 },
  { word: "life skill", meaning: ["kĩ năng sống"], unit: 8, grade: 11 },
  { word: "make use of", meaning: ["tận dụng"], unit: 8, grade: 11 },
  { word: "manage", meaning: ["quản lí"], unit: 8, grade: 11 },
  { word: "measure", meaning: ["đo"], unit: 8, grade: 11 },
  { word: "money management skill", meaning: ["kĩ năng quản lí tiền"], unit: 8, grade: 11 },
  { word: "non-stick container", meaning: ["nồi chống dính"], unit: 8, grade: 11 },
  { word: "remove", meaning: ["lấy ra", "loại bỏ"], unit: 8, grade: 11 },
  { word: "responsibility", meaning: ["sự chịu trách nhiệm", "trách nhiệm"], unit: 8, grade: 11 },
  { word: "responsible", meaning: ["có trách nhiệm"], unit: 8, grade: 11 },
  { word: "rice cooker", meaning: ["nồi cơm điện"], unit: 8, grade: 11 },
  { word: "self-motivated", meaning: ["có động lực", "năng nổ"], unit: 8, grade: 11 },
  { word: "self-study", meaning: ["sự tự học"], unit: 8, grade: 11 },
  { word: "time management skill", meaning: ["kĩ năng quản lí thời gian"], unit: 8, grade: 11 },

  // UNIT 9
  { word: "admit", meaning: ["thú nhận"], unit: 9, grade: 11 },
  { word: "alcohol", meaning: ["đồ uống có cồn", "rượu", "bia"], unit: 9, grade: 11 },
  { word: "anxiety", meaning: ["sự lo lắng"], unit: 9, grade: 11 },
  { word: "ashamed", meaning: ["xấu hổ"], unit: 9, grade: 11 },
  { word: "awareness", meaning: ["nhận thức"], unit: 9, grade: 11 },
  { word: "body shaming", meaning: ["sự chế nhạo ngoại hình", "miệt thị ngoại hình"], unit: 9, grade: 11 },
  { word: "bully", meaning: ["bắt nạt"], unit: 9, grade: 11 },
  { word: "campaign", meaning: ["chiến dịch"], unit: 9, grade: 11 },
  { word: "crime", meaning: ["tội phạm"], unit: 9, grade: 11 },
  { word: "depression", meaning: ["sự trầm cảm"], unit: 9, grade: 11 },
  { word: "drug", meaning: ["ma tuý"], unit: 9, grade: 11 },
  { word: "hang out", meaning: ["đi chơi"], unit: 9, grade: 11 },
  { word: "lie", meaning: ["lời nói dối"], unit: 9, grade: 11 },
  { word: "make fun of", meaning: ["trêu chọc", "chế giễu"], unit: 9, grade: 11 },
  { word: "obey", meaning: ["tuân thủ"], unit: 9, grade: 11 },
  { word: "offensive", meaning: ["gây xúc phạm"], unit: 9, grade: 11 },
  { word: "overpopulation", meaning: ["sự quá tải dân số"], unit: 9, grade: 11 },
  { word: "peer pressure", meaning: ["áp lực từ bạn bè", "áp lực đồng trang lứa"], unit: 9, grade: 11 },
  { word: "physical", meaning: ["về mặt thể chất"], unit: 9, grade: 11 },
  { word: "poverty", meaning: ["sự nghèo đói"], unit: 9, grade: 11 },
  { word: "proposal", meaning: ["lời đề xuất", "bản đề xuất"], unit: 9, grade: 11 },
  { word: "propose", meaning: ["đề xuất"], unit: 9, grade: 11 },
  { word: "self-confidence", meaning: ["sự tự tin vào bản thân"], unit: 9, grade: 11 },
  { word: "skip", meaning: ["trốn", "bỏ"], unit: 9, grade: 11 },
  { word: "stand up to", meaning: ["đứng lên chống lại"], unit: 9, grade: 11 },
  { word: "struggle", meaning: ["đấu tranh"], unit: 9, grade: 11 },
  { word: "the odd one out", meaning: ["kẻ khác biệt", "người khác biệt"], unit: 9, grade: 11 },
  { word: "the poverty line", meaning: ["mức nghèo đói"], unit: 9, grade: 11 },
  { word: "verbal", meaning: ["bằng lời"], unit: 9, grade: 11 },
  { word: "victim", meaning: ["nạn nhân"], unit: 9, grade: 11 },
  { word: "violent", meaning: ["sử dụng vũ lực", "bạo lực"], unit: 9, grade: 11 },

  // UNIT 10
  { word: "biodiversity", meaning: ["đa dạng sinh học"], unit: 10, grade: 11 },
  { word: "conservation", meaning: ["sự bảo tồn thiên nhiên", "bảo tồn"], unit: 10, grade: 11 },
  { word: "coral reef", meaning: ["rạn san hô"], unit: 10, grade: 11 },
  { word: "delta", meaning: ["đồng bằng"], unit: 10, grade: 11 },
  { word: "destroy", meaning: ["phá huỷ"], unit: 10, grade: 11 },
  { word: "ecosystem", meaning: ["hệ sinh thái"], unit: 10, grade: 11 },
  { word: "endangered", meaning: ["bị nguy hiểm"], unit: 10, grade: 11 },
  { word: "fauna", meaning: ["động vật"], unit: 10, grade: 11 },
  { word: "flora", meaning: ["thực vật"], unit: 10, grade: 11 },
  { word: "food chain", meaning: ["chuỗi thức ăn"], unit: 10, grade: 11 },
  { word: "green", meaning: ["xanh", "lối sống xanh"], unit: 10, grade: 11 },
  { word: "habitat", meaning: ["khu vực sống", "môi trường sống"], unit: 10, grade: 11 },
  { word: "living things", meaning: ["các sinh vật sống"], unit: 10, grade: 11 },
  { word: "mammal", meaning: ["động vật có vú"], unit: 10, grade: 11 },
  { word: "national park", meaning: ["rừng quốc gia"], unit: 10, grade: 11 },
  { word: "native", meaning: ["tự nhiên", "bản địa"], unit: 10, grade: 11 },
  { word: "natural resources", meaning: ["tài nguyên thiên nhiên"], unit: 10, grade: 11 },
  { word: "pangolin", meaning: ["con tê tê"], unit: 10, grade: 11 },
  { word: "resource", meaning: ["nguồn lực", "tài nguyên"], unit: 10, grade: 11 },
  { word: "species", meaning: ["loài"], unit: 10, grade: 11 },
  { word: "tropical forest", meaning: ["rừng nhiệt đới"], unit: 10, grade: 11 },
  { word: "wildlife", meaning: ["động vật hoang dã"], unit: 10, grade: 11 },


    //Grade12
  // UNIT 1
  { word: "Account", meaning: ["câu chuyện"], unit: 1, grade: 12 },
  { word: "Achievement", meaning: ["thành tích", "thành tựu"], unit: 1, grade: 12 },
  { word: "Admire", meaning: ["ngưỡng mộ"], unit: 1, grade: 12 },
  { word: "Adopt", meaning: ["nhận con nuôi"], unit: 1, grade: 12 },
  { word: "Animated", meaning: ["hoạt hình"], unit: 1, grade: 12 },
  { word: "Attack", meaning: ["cuộc tấn công", "tấn công"], unit: 1, grade: 12 },
  { word: "Attend (school/ college)", meaning: ["đi học (trường, trường đại học, cao đẳng)"], unit: 1, grade: 12 },
  { word: "Battle", meaning: ["chiến trường"], unit: 1, grade: 12 },
  { word: "Biography", meaning: ["tiểu sử"], unit: 1, grade: 12 },
  { word: "Biological", meaning: ["(quan hệ) ruột thịt"], unit: 1, grade: 12 },
  { word: "Bond", meaning: ["kết thân (với ai)"], unit: 1, grade: 12 },
  { word: "Cancer", meaning: ["ung thư"], unit: 1, grade: 12 },
  { word: "Carry out", meaning: ["tiến hành"], unit: 1, grade: 12 },
  { word: "Childhood", meaning: ["tuổi thơ"], unit: 1, grade: 12 },
  { word: "Communist Party of Viet Nam", meaning: ["Đảng Cộng sản Việt Nam"], unit: 1, grade: 12 },
  { word: "Death", meaning: ["cái chết"], unit: 1, grade: 12 },
  { word: "Defeat", meaning: ["đánh bại"], unit: 1, grade: 12 },
  { word: "Devote to", meaning: ["cống hiến (cho)"], unit: 1, grade: 12 },
  { word: "Drop out (of)", meaning: ["bỏ học"], unit: 1, grade: 12 },
  { word: "Enemy", meaning: ["kẻ thù"], unit: 1, grade: 12 },
  { word: "Genius", meaning: ["thiên tài"], unit: 1, grade: 12 },
  { word: "Hero", meaning: ["anh hùng"], unit: 1, grade: 12 },
  { word: "Marriage", meaning: ["cuộc hôn nhân"], unit: 1, grade: 12 },
  { word: "Military", meaning: ["quân đội"], unit: 1, grade: 12 },
  { word: "On cloud nine/ on top of the world/ over the moon", meaning: ["rất vui sướng", "hạnh phúc"], unit: 1, grade: 12 },
  { word: "Pancreatic", meaning: ["liên quan tới tuyến tuỵ"], unit: 1, grade: 12 },
  { word: "Pass away", meaning: ["qua đời"], unit: 1, grade: 12 },
  { word: "Poem", meaning: ["bài thơ"], unit: 1, grade: 12 },
  { word: "Poetry", meaning: ["thơ ca"], unit: 1, grade: 12 },
  { word: "Resign", meaning: ["từ chức"], unit: 1, grade: 12 },
  { word: "Resistance war", meaning: ["cuộc kháng chiến"], unit: 1, grade: 12 },
  { word: "Rule", meaning: ["sự trị vì", "trị vì"], unit: 1, grade: 12 },
  { word: "Youth", meaning: ["tuổi trẻ"], unit: 1, grade: 12 },

  // UNIT 2
  { word: "Admire", meaning: ["ngắm nhìn", "chiêm ngưỡng"], unit: 2, grade: 12 },
  { word: "Anxiety", meaning: ["sự bồn chồn", "lo lắng"], unit: 2, grade: 12 },
  { word: "Appreciate", meaning: ["thưởng thức", "trân trọng"], unit: 2, grade: 12 },
  { word: "Bamboo dancing", meaning: ["nhảy sạp"], unit: 2, grade: 12 },
  { word: "Captivate", meaning: ["thu hút", "cuốn hút"], unit: 2, grade: 12 },
  { word: "Celebrate", meaning: ["tổ chức", "mừng"], unit: 2, grade: 12 },
  { word: "Confusion", meaning: ["sự khó hiểu", "sự hỗn độn", "sự rối rắm"], unit: 2, grade: 12 },
  { word: "Costume", meaning: ["trang phục"], unit: 2, grade: 12 },
  { word: "Cuisine", meaning: ["ẩm thực"], unit: 2, grade: 12 },
  { word: "Cultural", meaning: ["thuộc về văn hoá"], unit: 2, grade: 12 },
  { word: "Culture shock", meaning: ["sốc văn hoá"], unit: 2, grade: 12 },
  { word: "Custom", meaning: ["phong tục"], unit: 2, grade: 12 },
  { word: "Diversity", meaning: ["sự đa dạng"], unit: 2, grade: 12 },
  { word: "Extracurricular", meaning: ["ngoại khoá"], unit: 2, grade: 12 },
  { word: "Festivity", meaning: ["ngày hội"], unit: 2, grade: 12 },
  { word: "Globalisation", meaning: ["sự toàn cầu hoá"], unit: 2, grade: 12 },
  { word: "Identity", meaning: ["bản sắc", "đặc điểm nhận dạng"], unit: 2, grade: 12 },
  { word: "Keep up with", meaning: ["bắt kịp với", "theo kịp"], unit: 2, grade: 12 },
  { word: "Lifestyle", meaning: ["lối sống"], unit: 2, grade: 12 },
  { word: "Multicultural", meaning: ["tính đa văn hoá"], unit: 2, grade: 12 },
  { word: "Origin", meaning: ["nguồn gốc"], unit: 2, grade: 12 },
  { word: "Popularity", meaning: ["sự phổ biến", "sự thông dụng"], unit: 2, grade: 12 },
  { word: "Speciality", meaning: ["đặc sản"], unit: 2, grade: 12 },
  { word: "Staple", meaning: ["cơ bản", "chủ yếu"], unit: 2, grade: 12 },
  { word: "Tasty", meaning: ["ngon"], unit: 2, grade: 12 },
  { word: "Traditional", meaning: ["truyền thống"], unit: 2, grade: 12 },
  { word: "Trend", meaning: ["xu hướng"], unit: 2, grade: 12 },
  { word: "Tug of war", meaning: ["trò chơi kéo co"], unit: 2, grade: 12 },

  // UNIT 3
  { word: "Carbon footprint", meaning: ["tổng lượng phát thải khí nhà kính"], unit: 3, grade: 12 },
  { word: "Cardboard", meaning: ["bìa cứng", "làm bằng bìa cứng"], unit: 3, grade: 12 },
  { word: "Clean up", meaning: ["dọn dẹp"], unit: 3, grade: 12 },
  { word: "Compost", meaning: ["phân hữu cơ"], unit: 3, grade: 12 },
  { word: "Container", meaning: ["thùng", "hộp", "gói"], unit: 3, grade: 12 },
  { word: "Contaminated", meaning: ["nhiễm độc", "nhiễm khuẩn"], unit: 3, grade: 12 },
  { word: "Decompose", meaning: ["phân huỷ"], unit: 3, grade: 12 },
  { word: "Eco-friendly", meaning: ["thân thiện/ tốt cho hệ sinh thái, môi trường"], unit: 3, grade: 12 },
  { word: "Fruit peel", meaning: ["vỏ hoa quả"], unit: 3, grade: 12 },
  { word: "Household waste", meaning: ["rác thải sinh hoạt"], unit: 3, grade: 12 },
  { word: "In the long run", meaning: ["về lâu dài"], unit: 3, grade: 12 },
  { word: "In the long/ medium/ short term", meaning: ["về lâu dài", "trong thời gian không xa", "trong thời gian trước mắt"], unit: 3, grade: 12 },
  { word: "Landfill", meaning: ["bãi chôn rác"], unit: 3, grade: 12 },
  { word: "Layer", meaning: ["lớp"], unit: 3, grade: 12 },
  { word: "Leftover", meaning: ["thức ăn thừa"], unit: 3, grade: 12 },
  { word: "Packaging", meaning: ["bao bì"], unit: 3, grade: 12 },
  { word: "Pile", meaning: ["chồng", "đống"], unit: 3, grade: 12 },
  { word: "Reusable", meaning: ["tái sử dụng được"], unit: 3, grade: 12 },
  { word: "Reuse", meaning: ["tái sử dụng"], unit: 3, grade: 12 },
  { word: "Rinse out", meaning: ["xối nước", "rửa sạch"], unit: 3, grade: 12 },
  { word: "Single-use", meaning: ["dùng một lần"], unit: 3, grade: 12 },
  { word: "Waste", meaning: ["rác thải"], unit: 3, grade: 12 },

  // UNIT 4
  { word: "Afford", meaning: ["có đủ tiền", "có khả năng chi trả"], unit: 4, grade: 12 },
  { word: "Colonial", meaning: ["thuộc địa", "thuộc dân"], unit: 4, grade: 12 },
  { word: "Concern", meaning: ["sự lo lắng"], unit: 4, grade: 12 },
  { word: "Decrease", meaning: ["giảm", "hạ xuống"], unit: 4, grade: 12 },
  { word: "Expand", meaning: ["mở rộng (về diện tích)"], unit: 4, grade: 12 },
  { word: "Gradually", meaning: ["dần dần", "từ từ"], unit: 4, grade: 12 },
  { word: "Housing", meaning: ["nhà ở"], unit: 4, grade: 12 },
  { word: "Leisure", meaning: ["sự giải trí", "thư giãn"], unit: 4, grade: 12 },
  { word: "Proportion", meaning: ["tỉ lệ"], unit: 4, grade: 12 },
  { word: "Rapidly", meaning: ["rất nhanh", "với tốc độ cao"], unit: 4, grade: 12 },
  { word: "Reliable", meaning: ["đáng tin cậy"], unit: 4, grade: 12 },
  { word: "Resident", meaning: ["người dân"], unit: 4, grade: 12 },
  { word: "Rush hour", meaning: ["giờ cao điểm"], unit: 4, grade: 12 },
  { word: "Seek", meaning: ["tìm kiếm"], unit: 4, grade: 12 },
  { word: "Unemployment", meaning: ["tình trạng thất nghiệp", "số người không có việc làm"], unit: 4, grade: 12 },
  { word: "Urban", meaning: ["thuộc về đô thị"], unit: 4, grade: 12 },

  // UNIT 5
  { word: "Application letter", meaning: ["thư xin việc"], unit: 5, grade: 12 },
  { word: "Bonus", meaning: ["tiền thưởng"], unit: 5, grade: 12 },
  { word: "Casual", meaning: ["theo thời vụ", "tạm thời"], unit: 5, grade: 12 },
  { word: "Challenging", meaning: ["thách thức"], unit: 5, grade: 12 },
  { word: "Flexible", meaning: ["linh hoạt"], unit: 5, grade: 12 },
  { word: "Footstep", meaning: ["bước chân", "truyền thống gia đình"], unit: 5, grade: 12 },
  { word: "Employ", meaning: ["tuyển dụng"], unit: 5, grade: 12 },
  { word: "Nine-to-five", meaning: ["giờ hành chính"], unit: 5, grade: 12 },
  { word: "On-the-job", meaning: ["trong công việc", "khi đang làm việc"], unit: 5, grade: 12 },
  { word: "Overtime", meaning: ["ngoài giờ"], unit: 5, grade: 12 },
  { word: "Part-time", meaning: ["bán thời gian"], unit: 5, grade: 12 },
  { word: "Repetitive", meaning: ["lặp đi lặp lại"], unit: 5, grade: 12 },
  { word: "Rewarding", meaning: ["xứng đáng"], unit: 5, grade: 12 },
  { word: "Shift", meaning: ["ca làm việc"], unit: 5, grade: 12 },
  { word: "Stressful", meaning: ["áp lực", "căng thẳng"], unit: 5, grade: 12 },
  { word: "Unpaid", meaning: ["không được trả lương"], unit: 5, grade: 12 },
  { word: "Wage", meaning: ["tiền công (trả theo giờ hoặc theo khối lượng công việc)"], unit: 5, grade: 12 },
  { word: "Wait on tables", meaning: ["phục vụ đồ ăn thức uống cho khách trong nhà hàng"], unit: 5, grade: 12 },
  { word: "Well-paid", meaning: ["được trả lương cao"], unit: 5, grade: 12 },
  { word: "Vacancy", meaning: ["vị trí công việc còn trống"], unit: 5, grade: 12 },

  // UNIT 6
  { word: "Activate", meaning: ["kích hoạt", "khởi động"], unit: 6, grade: 12 },
  { word: "Advanced", meaning: ["tiên tiến", "trình độ cao"], unit: 6, grade: 12 },
  { word: "Analyse", meaning: ["phân tích"], unit: 6, grade: 12 },
  { word: "Application", meaning: ["sự ứng dụng", "sự áp dụng"], unit: 6, grade: 12 },
  { word: "Artificial intelligence (AI)", meaning: ["trí thông minh nhân tạo"], unit: 6, grade: 12 },
  { word: "Capable", meaning: ["có khả năng"], unit: 6, grade: 12 },
  { word: "Chatbot", meaning: ["hộp trò chuyện"], unit: 6, grade: 12 },
  { word: "Data", meaning: ["dữ liệu"], unit: 6, grade: 12 },
  { word: "Digital", meaning: ["thuộc kĩ thuật số"], unit: 6, grade: 12 },
  { word: "Evolution", meaning: ["sự tiến hoá", "sự phát triển"], unit: 6, grade: 12 },
  { word: "Facial recognition", meaning: ["khả năng nhận diện khuôn mặt"], unit: 6, grade: 12 },
  { word: "Function", meaning: ["chức năng", "nhiệm vụ"], unit: 6, grade: 12 },
  { word: "Hands-on", meaning: ["thực tiễn", "trực tiếp"], unit: 6, grade: 12 },
  { word: "Human-like", meaning: ["giống con người"], unit: 6, grade: 12 },
  { word: "Interact", meaning: ["tương tác"], unit: 6, grade: 12 },
  { word: "Personalised", meaning: ["được cá nhân hoá"], unit: 6, grade: 12 },
  { word: "Platform", meaning: ["nền tảng (công nghệ)"], unit: 6, grade: 12 },
  { word: "Portfolio", meaning: ["hồ sơ"], unit: 6, grade: 12 },
  { word: "Programme", meaning: ["lập trình"], unit: 6, grade: 12 },
  { word: "Robotic", meaning: ["thuộc rô bốt"], unit: 6, grade: 12 },
  { word: "Upgrade", meaning: ["nâng cấp"], unit: 6, grade: 12 },
  { word: "Virtual reality", meaning: ["thực tế ảo"], unit: 6, grade: 12 },
  { word: "Voice command", meaning: ["ra lệnh bằng giọng nói"], unit: 6, grade: 12 },

  // UNIT 7
  { word: "Accessible", meaning: ["có thể tiếp cận được"], unit: 7, grade: 12 },
  { word: "Account for", meaning: ["chiếm (tỉ lệ)"], unit: 7, grade: 12 },
  { word: "Advert", meaning: ["quảng cáo"], unit: 7, grade: 12 },
  { word: "As opposed to", meaning: ["khác với", "đối lập với"], unit: 7, grade: 12 },
  { word: "Audio", meaning: ["bằng/có âm thanh"], unit: 7, grade: 12 },
  { word: "Bias", meaning: ["thiên kiến", "thiên vị"], unit: 7, grade: 12 },
  { word: "Broadcast", meaning: ["(chương trình) phát sóng"], unit: 7, grade: 12 },
  { word: "By contrast", meaning: ["ngược lại"], unit: 7, grade: 12 },
  { word: "Credible", meaning: ["đáng tin cậy"], unit: 7, grade: 12 },
  { word: "Digital billboard", meaning: ["bảng quảng cáo kĩ thuật số"], unit: 7, grade: 12 },
  { word: "Discount", meaning: ["sự hạ giá"], unit: 7, grade: 12 },
  { word: "Distribute", meaning: ["phân phát", "phân phối"], unit: 7, grade: 12 },
  { word: "Fact-check", meaning: ["kiểm chứng thông tin"], unit: 7, grade: 12 },
  { word: "Fake news", meaning: ["tin giả", "tin bịa đặt"], unit: 7, grade: 12 },
  { word: "Instant", meaning: ["nhanh chóng", "ngay lập tức"], unit: 7, grade: 12 },
  { word: "Interactive", meaning: ["có thể tương tác được"], unit: 7, grade: 12 },
  { word: "Loudspeaker", meaning: ["loa phát thanh"], unit: 7, grade: 12 },
  { word: "Mass media", meaning: ["phương tiện truyền thông đại chúng"], unit: 7, grade: 12 },
  { word: "Meanwhile", meaning: ["trong khi đó"], unit: 7, grade: 12 },
  { word: "Place", meaning: ["đặt", "rao", "đăng (tin, quảng cáo)"], unit: 7, grade: 12 },
  { word: "Presence", meaning: ["sức thu hút", "sức ảnh hưởng"], unit: 7, grade: 12 },
  { word: "Profit-making", meaning: ["tạo lợi nhuận"], unit: 7, grade: 12 },
  { word: "Publicity", meaning: ["sự quan tâm, chú ý của công chúng"], unit: 7, grade: 12 },
  { word: "Reliable", meaning: ["xác thực"], unit: 7, grade: 12 },
  { word: "Source", meaning: ["nguồn tin"], unit: 7, grade: 12 },
  { word: "Spread", meaning: ["lan truyền"], unit: 7, grade: 12 },
  { word: "The press", meaning: ["báo chí"], unit: 7, grade: 12 },
  { word: "Update", meaning: ["cập nhật"], unit: 7, grade: 12 },
  { word: "Viewer", meaning: ["người xem"], unit: 7, grade: 12 },
  { word: "Visual", meaning: ["bằng/có hình ảnh"], unit: 7, grade: 12 },

  // UNIT 8
  { word: "Body part", meaning: ["bộ phận cơ thể"], unit: 8, grade: 12 },
  { word: "Captivity", meaning: ["sự nuôi nhốt"], unit: 8, grade: 12 },
  { word: "Conservation", meaning: ["sự bảo vệ", "sự bảo tồn"], unit: 8, grade: 12 },
  { word: "Conserve", meaning: ["bảo vệ", "bảo tồn"], unit: 8, grade: 12 },
  { word: "Coral", meaning: ["san hô"], unit: 8, grade: 12 },
  { word: "Critically endangered", meaning: ["bị đe doạ nghiêm trọng"], unit: 8, grade: 12 },
  { word: "Debris", meaning: ["mảnh vỡ", "mảnh vụn"], unit: 8, grade: 12 },
  { word: "Degrade", meaning: ["xuống cấp"], unit: 8, grade: 12 },
  { word: "Enclosure", meaning: ["chuồng thú"], unit: 8, grade: 12 },
  { word: "Endangered", meaning: ["bị đe doạ", "gặp nguy hiểm"], unit: 8, grade: 12 },
  { word: "Extinct", meaning: ["tuyệt chủng"], unit: 8, grade: 12 },
  { word: "Forest clearance", meaning: ["sự chặt, phá rừng"], unit: 8, grade: 12 },
  { word: "House", meaning: ["cung cấp nơi ở"], unit: 8, grade: 12 },
  { word: "Mammal", meaning: ["động vật có vú"], unit: 8, grade: 12 },
  { word: "Marine", meaning: ["thuộc về biển"], unit: 8, grade: 12 },
  { word: "Monitor", meaning: ["giám sát"], unit: 8, grade: 12 },
  { word: "Nursery", meaning: ["vườn ươm"], unit: 8, grade: 12 },
  { word: "Poach", meaning: ["săn bắn bất hợp pháp"], unit: 8, grade: 12 },
  { word: "Primate", meaning: ["bộ (họ) linh trưởng"], unit: 8, grade: 12 },
  { word: "Rare", meaning: ["hiếm", "quý hiếm"], unit: 8, grade: 12 },
  { word: "Release", meaning: ["thả"], unit: 8, grade: 12 },
  { word: "Rescue", meaning: ["giải cứu"], unit: 8, grade: 12 },
  { word: "Sea turtle", meaning: ["rùa biển"], unit: 8, grade: 12 },
  { word: "Sign language", meaning: ["ngôn ngữ kí hiệu"], unit: 8, grade: 12 },
  { word: "Spawning ground", meaning: ["nơi đẻ trứng"], unit: 8, grade: 12 },
  { word: "Survive", meaning: ["tồn tại"], unit: 8, grade: 12 },
  { word: "Threatened", meaning: ["bị đe doạ"], unit: 8, grade: 12 },
  { word: "Vulnerable", meaning: ["dễ bị tổn thương"], unit: 8, grade: 12 },

  // UNIT 9
  { word: "Automate", meaning: ["tự động hoá"], unit: 9, grade: 12 },
  { word: "Adapt", meaning: ["thay đổi cho phù hợp", "thích ứng theo", "thích nghi"], unit: 9, grade: 12 },
  { word: "Character", meaning: ["phẩm chất", "đặc điểm tính cách"], unit: 9, grade: 12 },
  { word: "Childminder", meaning: ["người trông trẻ"], unit: 9, grade: 12 },
  { word: "Cut down on", meaning: ["cắt giảm", "giảm bớt"], unit: 9, grade: 12 },
  { word: "CV (curriculum vitae)", meaning: ["sơ yếu lí lịch"], unit: 9, grade: 12 },
  { word: "Fascinating", meaning: ["cực kì thú vị và hấp dẫn"], unit: 9, grade: 12 },
  { word: "In demand", meaning: ["có nhu cầu", "được mọi người mong muốn"], unit: 9, grade: 12 },
  { word: "Get on with", meaning: ["hoà hợp với", "có mối quan hệ tốt với"], unit: 9, grade: 12 },
  { word: "Go in for", meaning: ["đam mê", "theo đuổi một sở thích"], unit: 9, grade: 12 },
  { word: "Live up to", meaning: ["làm theo sự mong muốn", "kì vọng của ai đó"], unit: 9, grade: 12 },
  { word: "Look down on", meaning: ["coi thường người khác", "cho rằng mình hơn người"], unit: 9, grade: 12 },
  { word: "Obsolete", meaning: ["lỗi thời", "không còn được sử dụng", "không thịnh hành"], unit: 9, grade: 12 },
  { word: "Passion", meaning: ["niềm đam mê", "say mê"], unit: 9, grade: 12 },
  { word: "Passionate", meaning: ["có niềm đam mê với/dành cho"], unit: 9, grade: 12 },
  { word: "Position", meaning: ["vị trí việc làm"], unit: 9, grade: 12 },
  { word: "Pursue", meaning: ["theo đuổi"], unit: 9, grade: 12 },
  { word: "Put up with", meaning: ["chịu đựng"], unit: 9, grade: 12 },
  { word: "Soft skills", meaning: ["các kĩ năng mềm"], unit: 9, grade: 12 },
  { word: "Specialty", meaning: ["chuyên ngành"], unit: 9, grade: 12 },
  { word: "Take into account", meaning: ["cân nhắc", "xem xét"], unit: 9, grade: 12 },
  { word: "Tutor", meaning: ["gia sư", "giáo viên dạy kèm nhóm học sinh"], unit: 9, grade: 12 },
  { word: "Work experience", meaning: ["kinh nghiệm làm việc"], unit: 9, grade: 12 },

  // UNIT 10
  { word: "Acquire", meaning: ["có được", "đạt được"], unit: 10, grade: 12 },
  { word: "Adult education", meaning: ["giáo dục cho người lớn"], unit: 10, grade: 12 },
  { word: "Boost", meaning: ["tăng cường", "cải thiện"], unit: 10, grade: 12 },
  { word: "Broaden", meaning: ["mở mang", "mở rộng"], unit: 10, grade: 12 },
  { word: "Brush up", meaning: ["ôn lại", "học lại"], unit: 10, grade: 12 },
  { word: "Complex", meaning: ["phức tạp"], unit: 10, grade: 12 },
  { word: "Determination", meaning: ["sự quyết tâm"], unit: 10, grade: 12 },
  { word: "Distance learning", meaning: ["học từ xa"], unit: 10, grade: 12 },
  { word: "Distraction", meaning: ["sự phân tâm", "sự sao lãng"], unit: 10, grade: 12 },
  { word: "Hardship", meaning: ["sự khó khăn", "vất vả"], unit: 10, grade: 12 },
  { word: "Governess", meaning: ["gia sư", "giáo viên dạy kèm tại nhà"], unit: 10, grade: 12 },
  { word: "Imprison", meaning: ["giam cầm", "cầm tù"], unit: 10, grade: 12 },
  { word: "Informed", meaning: ["có kiến thức về", "có hiểu biết", "được cung cấp đầy đủ thông tin"], unit: 10, grade: 12 },
  { word: "Intelligence", meaning: ["tình báo"], unit: 10, grade: 12 },
  { word: "Learning community", meaning: ["cộng đồng học tập"], unit: 10, grade: 12 },
  { word: "Maintain", meaning: ["duy trì", "giữ được"], unit: 10, grade: 12 },
  { word: "Martial art", meaning: ["võ thuật"], unit: 10, grade: 12 },
  { word: "Molecular Biology", meaning: ["ngành sinh học phân tử"], unit: 10, grade: 12 },
  { word: "Night school", meaning: ["lớp học buổi tối (dành cho người lớn)"], unit: 10, grade: 12 },
  { word: "Psychology", meaning: ["ngành tâm lí học"], unit: 10, grade: 12 },
  { word: "Relevant", meaning: ["phù hợp", "thích hợp"], unit: 10, grade: 12 },
  { word: "Well-rounded", meaning: ["được phát triển một cách toàn diện"], unit: 10, grade: 12 },
  { word: "Widen", meaning: ["mở rộng", "tăng thêm"], unit: 10, grade: 12 },
  { word: "Wonder", meaning: ["thắc mắc", "băn khoăn"], unit: 10, grade: 12 }
];